@hostname = http://127.0.0.1:8000/
# @hostname = https://projet-master-dev-back.herokuapp.com/
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVfbnVtIjoiMTIzNCIsImV4cCI6MTY1NjQxMjQwNX0.hVowfb9kypxRRSO4NEA7Gk0W3wWeZahQnKth7Quc02o


###
POST {{hostname}}login
Content-Type: application/json

{
    "phone_num": "1234",
    "password" : "malika_pass"
}

###





### plans====================
GET  {{hostname}}plan/
Authorization : Bearer {{token}}
###

GET  {{hostname}}plan/today
Authorization : Bearer {{token}}

###

GET  {{hostname}}plan/all

###

### animateur ===================
GET {{hostname}}animateur/list

###

GET {{hostname}}animateur/
Authorization : Bearer {{token}}
###

POST {{hostname}}animateur
Content-Type: application/json

{
    "phone_num" : "1234",
    "full_name" : "malika",
    "password" : "malika_pass",
    "zone" : 0,
    "last_day" : 1,
    "max_days" : 5
}


###

PUT {{hostname}}animateur/2
Authorization: bearer {{token}}




### pdvs ========================
GET {{hostname}}pos
###


POST {{hostname}}pos/
Content-Type: application/json

{
    "phone_num" : "123340",
    "x" : 5,
    "y" : 5,
    "zone" : 0,
    "priority" : 1
}

###

###
GET {{hostname}}pos/2